### ISSUE TITLE
建議logging dependency改為slf4j

### ISSUE THREAD

**Issue by haha02** [ECPay/ECPayAIO_Java#3]
如題
使用slf4j可以讓user自己決定logging的實作要怎麼選用
以一個library/SDK的觀點來說是比較好的
自帶log4j在某些情況例如JBoss application server自帶logging framework的時候容易造成衝突
而且log4j 1.2已經很舊很舊了，使用上有諸多不便

**Comment by AllennChang** [comment]
您好, 感謝您的回應, 我會反應給我們開發團隊,再次謝謝您的建議
